### ISSUE TITLE
Create a README file in analysis folder

### ISSUE THREAD

**Issue by Reagen** [astrochun/Zcalbase_gal#47]
Create a README.md file that explains the way to run analysis 
Lives in hotfix/v0.9.1

**Comment by Reagen** [comment]
dataset = 'n_Bins'
y_correction = ''
n_split = 3
adaptive = True 
dustatten = True
mask = True

**Comment by astrochun** [comment]
Follow the above configuration but run with `feature/edit_hstack`.  Modify MSC to include path for `cly`
