### ISSUE TITLE
Adding manual_bin_grid.py to binning function

### ISSUE THREAD

**Issue by Reagen** [astrochun/Zcalbase_gal#89]
Last May, we talked about making a new binning plot to be used by n_bins_grid_analysis. I created the plot in plotting/manual_bin_grid, but did not implement it. This issue implements this new plot. It shades each bin and plots the mean of each R23 and O32 bin value. The file outputted name is currently manual_binning_shading.pdf

**Comment by astrochun** [comment]
@Reagen can you please change the title of this issue? It's easily confused with the PR.

**Comment by astrochun** [comment]
In this issue ticket, can you upload what this bin plot looks like?

**Comment by Reagen** [comment]
[manual_binning_shading.pdf](https://github.com/astrochun/Zcalbase_gal/files/5992318/manual_binning_shading.pdf)
